name: Automated Pipeline - DVC + MLflow

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  push:
    branches:
      - main
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python deps + dvc
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gs]" || pip install dvc

      - name: DVC pull (to be configured in future with remote dvc)
        run: |
          echo "Skipping dvc pull ."

      - name: Run pipeline via DVC
        run: |
          dvc repro --force

      - name: Show generated artifacts
        run: |
          ls -la models || true
          ls -la data/processed || true

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy (docker-compose)
        run: |
          docker-compose -f code/deployment/docker-compose.yml up -d --build
          echo "Deploying!"
